### ISSUE TITLE
DaVinci LGGO DCTL doesn't compile

### ISSUE THREAD

**Issue by thomjiji** [thatcherfreeman/utility-dctls#11]
Hey Thatcher,

The DaVinci LGGO DCTL doesn't have any effect when I drag the slider. It seems relates to the function `sample_color`, I remove this function and it compiles.

The [error log](https://github.com/user-attachments/files/17373384/davinci_resolve_intercepted.log) (intercepted from davinci_resolve.log file) is attached. It's running on an Apple silicon Mac.

**Comment by thatcherfreeman** [comment]
Hey thanks for reporting that bug, I've removed that function from that tool and it should work fine now. Thanks!
