### ISSUE TITLE
MTF Curve way too heavy on gpu

### ISSUE THREAD

**Issue by vicercolor** [thatcherfreeman/utility-dctls#13]
Hey thatcher. I’ve noticed some performance issues with the updated MTF Curve DCTL. The Gaussian blur works well visually, but it consistently pushes my GPU (RTX 4060) to 100% usage and often crashes the project. I find this a bit unusual because other GPU-intensive plugins like Dehancer, as well as tools like Texture Pop and Frequency Separation from Paul Dore, run without any issues on my system.

Do you think it would be possible to optimize the DCTL in a future update? Thanks for your work, despite the problem I was really pleased with the results I've got

**Comment by thatcherfreeman** [comment]
Hey, the reality is that DCTL does not allow for efficient blur kernels to be implemented. The more pixels sampled by the DCTL, the slower it will run. The lowest frequency blur band in the MTF curve DCTL requires a blur with a large radius to be applied. If you don't make use of the lowest frequency band, you could set the "Blur Scale" slider to 0.5 and then you'll get faster playback performance. Likewise, if you don't use the two lowest bands, you could set it to 0.25.

The reason those other tools have better playback performance are that OFX are expressive enough to use faster (IE decomposable) blur kernels. Texture pop is similar to OFX, and usually frequency separation DCTLs are used to treat relatively high frequency details, meaning that they end up using a small blur radius and can therefore get good performance with an inefficient approach like my tool uses.

Looking at my code, the main room I see for optimization is that I can make it run faster when the lower frequency sliders are set to their default positions. I'll check if there's low hanging fruit in terms of truncating the blur kernel, but I'm not optimistic on that front.

**Comment by thatcherfreeman** [comment]
Hey, just updated the DCTL to have the optimization discussed at the end of the previous comment

**Comment by vicercolor** [comment]
Thank you for the response; it was very insightful. I also appreciate the update! I'll test it out along with what you've mentioned.
