### ISSUE TITLE
Halation DCTL causes the thumbnail/node preview to go black

### ISSUE THREAD

**Issue by thomjiji** [thatcherfreeman/utility-dctls#8]
Hey! Thanks for this big pile of DCTLs. Here's a little issue that I find in Effects/Halation DCTL.

The Halation DCTL will cause the thumbnail/node preview to go black. Once I load that DCTL, the preview is gone. If I load that DCTL in my whole timeline, the thumbnails will all go black so that I can't navigate the timeline by looking at the thumbnails to find the next shot I'm interested to work in.

It's DaVinci Resolve 19b4 on M2 Ultra Mac Studio, node-based color-manged, working on DWG.

![disable_node](https://github.com/user-attachments/assets/911cf897-1b96-48d8-9890-66fb138f2c2c)
![enable_node](https://github.com/user-attachments/assets/0add9ba8-acfa-43cc-aa12-b02436e567b4)

**Comment by thomjiji** [comment]
Yeah, I read that this DCTL expect Linear input, so I changed the node Gamma to Linear by right click the node and select, select. But the issue still persists.

**Comment by thatcherfreeman** [comment]
Hey, just pushed an update to the dctl, lmk if it's not fixed for you.

**Comment by thomjiji** [comment]
Sorry for the late reply, it fixed it magically, thanks! I hope I can understand that math and code.
